name: Build Pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:
    inputs:
      enable_quality_gates:
        description: "Enable quality gates in the reusable workflow"
        required: false
        type: boolean
        default: true
      enable_release:
        description: "Enable release in the reusable workflow"
        required: false
        type: boolean
        default: false

jobs:
  call-build-workflow:
    uses: Xhaguatende/reusable-workflows/.github/workflows/dotnet-web-reusable.yml@main
    with:
      enable_quality_gates: ${{ inputs.enable_quality_gates }}
      enable_release: ${{ inputs.enable_release }}
      dotnet_version: "9.x"
      sonar_cloud_organization: "xhaguatende-01"
      sonar_cloud_project_key: "Xhaguatende_expense-tracker-backend"
      publish_project: "./ExpenseTracker.Api/ExpenseTracker.Api.csproj"
      docker_file: "./docker/Dockerfile.Api"
      docker_hub_repository: "expense-tracker-api"
      docker_image_title: "Expense Tracker API"
      docker_image_description: "Docker image for Expense Tracker API"
    secrets: inherit
